### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by moaoci**
ClsCDP and AutomateBrowser were modified to allow  these parameters browserType, new killExistingInstance and new additionnalInlineCommands so they reach LaunchBrowser.

browsers.bas was modified to better identify browser .exe path and to prevent from executing an uninstalled link.
public function browserStatus was created to identify if browser is «Not installed» «Available» or «Running»

### CODE REVIEW

**Comment by moaoci** [comment]
I expected that differences would be highlighted...   Did I not do something important ?

**Comment by moaoci** [comment]
I found my mistake: I didn't upload the files in the src directory....

**Comment by PerditionC** [comment]
I will look at the changes tonight and try to get them merged in.  Thank you.

**Comment by moaoci** [comment]
I will close this pull request and restart a new one so I can do it the right way.  Remember, it's my first time

**Pull request closed without merging**
